[package]
name = "init"
version = "0.1.0"
authors = ["txya900619 <wayne900619@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
